{% set name = "cornice" %}
{% set version = "6.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6edf6f206ff1c3d108d7a7b9ae640a2f4737cfc04f0914ccc4eefe511d3a8985

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pyramid >=1.7,<3
    - venusian

test:
  requires:
    - python {{ python_min }}
  imports:
    - cornice

about:
  home: https://github.com/Cornices/cornice
  summary: 'Cornice provides helpers to build & document Web Services with Pyramid.'
  description: |
    Cornice provides helpers to build & document REST-ish Web Services with Pyramid,
    with decent default behaviors. It takes care of following the HTTP specification
    in an automated way where possible. We designed and implemented cornice in a really
    simple way, so it is easy to use and you can get started in a matter of minutes.
  license: MPL-2.0
  license_file: LICENSE
  doc_url: https://cornice.readthedocs.io
  dev_url: https://github.com/Cornices/cornice

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
    - JamesMakela-NOAA
